//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_13_25.D2.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long StudId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
