//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_13_25.D2.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public long TutorId { get; set; }
        public string TutorName { get; set; }
        public string Expertise { get; set; }
        public Nullable<int> HourlyRate { get; set; }
        public string Email { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
    }
}
